### PR TITLE
Add a 'crypt' module to rust-g

### PR DESCRIPTION
**Pull request by steamp0rt**
Exposes 3 things: `bcrypt_hash(data)`, `bcrypt_verify(data)`, and `ed25519_verify(data, sig, pubkey)`

For `ed25519_verify`, all 3 arguments are hexadecimal.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
what for

**Comment by steamp0rt** [comment]
byond-less authentication

**Comment by steamp0rt** [comment]
(my implementation of no-byond auth uses bcrypt hashing for passwords, and ed25519 challenge-response for auto-logins)

**Comment by SpaceManiac** [comment]
I don't see anything especially wrong with these functions but I don't know of any codebase particularly interested in 3rd-party auth right now, so I won't be merging this.

**Pull request closed without merging**
