### PR TITLE
Adds toml2json feature

### PR DESCRIPTION
**Pull request by ZeWaka**
Based on https://github.com/ParadiseSS13/rust-g/pull/8

### CODE REVIEW

**Comment by ZeWaka** [comment]
mind you, the git test also failed locally. idk what the fuck is up with it

**Comment by optimumtact** [comment]
it bork

**Comment by optimumtact** [comment]
it's still broken

**Comment by Cyberboss** [comment]
> #69 

Nice.

**Comment by Mothblocks** [comment]
i'm gonna try to fix this up into a new pr

**Pull request closed without merging**
