### PR TITLE
Refactor logging to be based on an asynchronous tokio buffer

### PR DESCRIPTION
**Pull request by aspenluxxxy**

### CODE REVIEW

**Comment by optimumtact** [comment]
Isn't this overkill for logging? this will sureyl have a higher memory overhead and rust-g counts towards the memory limits

**Comment by actioninja** [comment]
Putnam was finding that rust-g was causing server stuttering when shitloads of logs got thrown at it. They made a threaded solution in extools.

**Comment by optimumtact** [comment]
I find that very hard to believe

**Comment by Cyberboss** [comment]
This is a good PR, but yeah I'd like to see a benchmark of the slowdown in the old logging method just so we're sure this is the cause

**Pull request closed without merging**
