### PR TITLE
Standardize redis_reliablequeue connect/disconnect output

### PR DESCRIPTION
**Pull request by ZeWaka**
Essentially makes it match the 
```json
{
  "success": bool
  "content": string
}
```
format instead of just returning the raw rust error through `?` propagation.

### CODE REVIEW

**Comment by ZeWaka** [comment]
should probably test this

**Comment by AffectedArc07** [comment]
> should probably test this

I can TM this on para, I know we use redis pubsub.

**Comment by ZeWaka** [comment]
i intend to get to this sometime now, since goon uses this in prod

**Comment by ZeWaka** [comment]
x

**Pull request merged**
