### PR TITLE
chore: routine updates

### PR DESCRIPTION
**Pull request by ZeWaka**
Basically `cargo upgrade` and `cargo update`, but manually done.

### #172 still applies

### CODE REVIEW

**Comment by AffectedArc07** [comment]
> # needs testing
> # especially redis on para maybe and goon

Our redis is already broke on latest, this might fix it.

**Comment by ZeWaka** [comment]
> > # needs testing
> > # especially redis on para maybe and goon
> 
> Our redis is already broke on latest, this might fix it.

hence my comment :)))))))))

**Comment by optimumtact** [comment]
looks good to me

**Comment by AffectedArc07** [comment]
Still busted

image

**Comment by AffectedArc07** [comment]
Merge reminder - patch for iconforge .dm file documentation header

**Comment by AffectedArc07** [comment]
Pubsub is still fucked on para - ill just revert to 0.25 on our patches and we can have an outstanding issue here for it.

**Pull request merged**
